spring:
  application:
    name: eureka-Server-HA

---

eureka:
  instance:
    hostname: eurekaServerA
  client:
    service-url:
      defaultZone: http://eurekaServerB:8762/eureka
server:
  port: 8761
spring:
  profiles: serverA

---

eureka:
  instance:
    hostname: eurekaServerB
  client:
    service-url:
      defaultZone: http://eurekaServerA:8761/eureka
server:
  port: 8762
spring:
  profiles: serverB